causes = [
r"\w+ was shot",
r"\w+ was pummeled",
r"\w+ was pricked",
r"\w+ walked into",
r"\w+ drowned",
r"\w+ experienced",
r"\w+ blew up",
r"\w+ was",
r"\w+ hit",
r"\w+ fell",
r"death.fell.accident.water",
r"\w+ went",
r"\w+ burned",
r"\w+ tried",
r"\w+ discovered the floor was lava",
r"\w+ froze",
r"death.attack.sting.item",
r"death.attack.witherSkull.item",
r"\w+ starved",
r"\w+ suffocated",
r"\w+ didn't want",
r"\w+ withered"
]