causes = [
r"\S+ was shot",
r"\S+ was pummeled",
r"\S+ was pricked",
r"\S+ walked into",
r"\S+ drowned",
r"\S+ experienced",
r"\S+ blew up",
r"\S+ was",
r"\S+ hit",
r"\S+ fell",
r"death.fell.accident.water",
r"\S+ went",
r"\S+ burned",
r"\S+ tried",
r"\S+ discovered the floor was lava",
r"\S+ froze",
r"death.attack.sting.item",
r"death.attack.witherSkull.item",
r"\S+ starved",
r"\S+ suffocated",
r"\S+ didn't want",
r"\S+ withered"
]